FROM node:14.20.0

RUN npm install -g npm@6.14.17

RUN node -v && npm -v && git --version && curl --version

WORKDIR /root
# Clone Shine Your Eye repo
# RUN git clone https://github.com/EiEResearch/shineyoureye-javascript

# COPY ./package*.json ./

# copy all files to the container
COPY . .

RUN npm install

#lint vue app
RUN (npm run lint -- --fix)

RUN (npm run prose)

# pull prose content into the app
RUN (cd /root/prose && git clone https://github.com/theyworkforyou/shineyoureye-prose.git)

# copy media files to dist
RUN (cp -R /root/prose/media/ /root/dist/)

# start the project
# RUN (cd /root/api && npm install)

# RUN (cd /root/api && export NODE_ENV=production && nohup `npm run start` &)

RUN echo 'build-completed'

EXPOSE 8080

CMD cd /root && npm run serve


